### ISSUE TITLE
Zweryfikować STOP 

### ISSUE THREAD

**Issue by janzeg** [janzeg/ms300-ecat-fb-indu#2]
Zweryfikować zachowanie falownika po wyzwoleniu komendy STOP. Podobno na falowniku f jest 0 i miga RUN

**Comment by janzeg** [comment]
Jak przechodzimy w control word z 16#E -> 16#F to falownik automatycznie wchodzi w RUN, ale nie wystawia zadanej częstotliwości - po prostu tak to działa. Dopiero jak dajemy 16#7F to falownik wchodzi w RUN.

**Comment by mszankowski** [comment]
zeby zmienic parametry trzeba "pozbyc sie" RUN. Mozna to zrobic zmieniajac status na INIT. Po zmianie parametrów ENABLE

**Comment by janzeg** [comment]
@mszankowski 
Jak coś to, żeby pozbyć się RUN wystarczy zdjąć z bloku Enable. Chyba to właśnie napisałeś powyżej, ale nie jestem pewny.

Teraz jeszcze sprawdziłem jak to dokładnie wygląda z tym hamowaniem. Jeżeli zamiast przechodzić z 16#7F -> 16#F, to przechodziłbym 16#7F -> 16#E to faktycznie schodziłby stop, ale falownik hamowałby wybiegiem, więc musi być tak jak jest teraz.
