### ISSUE TITLE
Status Fault/Warn - skrocenie kodu

### ISSUE THREAD

**Issue by mszankowski** [janzeg/ms300-ecat-fb-indu#3]
zmien zapis 
z:
IF Status.FaultCode <> 0 THEN
	Status.Fault := TRUE;
ELSE
	Status.Fault := FALSE;
END_IF
IF Status.WarningCode <> 0 THEN
	Status.Warning := TRUE;
ELSE
	Status.Warning := FALSE;
END_IF

na:
Status.Fault := Status.FaultCode <> 0 ;
Status.Warning := Status.WarningCode <> 0;

**Comment by janzeg** [comment]
Dzięki

**Comment by mszankowski** [comment]
poprawiłem i wrzuciłem pod 1.0.0.7
